import streamlit as st
import pandas as pd
import yfinance as yf
import requests
from datetime import datetime, timedelta

st.set_page_config(layout="wide", page_title="Institutional NSE Analytics Engine")

# =====================================================================
# API GATEWAY LAYER (VERIFIED BROWSER AGENTS)
# =====================================================================
def verify_yfinance_api():
    """Checks the health and uptime of the Yahoo Finance data stream."""
    try:
        df = yf.download("^NSEI", period="5d", interval="1d", progress=False)
        if df is None or df.empty:
            return "NO"
        return "YES"
    except Exception:
        return "NO"

def verify_nse_exchange_api():
    """Directly hits the NSE public data pipeline using standard browser headers to bypass cloud firewalls."""
    try:
        # Utilizing an incredibly stable official live endpoint to test connectivity
        url = "https://www.nseindia.com/api/marketStatus"
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept-Language": "en-US,en;q=0.9",
            "Accept-Encoding": "gzip, deflate, br"
        }
        
        # Establishing a valid session cookie cache before pinging endpoint
        session = requests.Session()
        session.get("https://www.nseindia.com", headers=headers, timeout=5)
        response = session.get(url, headers=headers, timeout=5)
        
        if response.status_code == 200 and "marketState" in response.json():
            return "YES"
        return "NO"
    except Exception:
        return "NO"

# =====================================================================
# CORE HISTORICAL RETRIEVAL LAYER (FIREWALL EVASION FEED)
# =====================================================================
def get_equity_history(symbol):
    """Fetches full historical market matrices bypassing standard API blocks."""
    try:
        # Falling back to a clean, structural historical alternative since yfinance handles
        # raw numeric tickers securely if suffix protocols are stripped or formatted correctly.
        # Alternatively, we format for the stable international pipeline.
        ticker = f"{symbol}.NS"
        df = yf.download(ticker, period="2mo", interval="1d", progress=False)
        
        if df is None or df.empty:
            return None
            
        # Flatten MultiIndex columns if generated by yfinance
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
            
        df.columns = [str(col).strip().upper() for col in df.columns]
        return df.copy()
    except Exception:
        return None

# =====================================================================
# QUANTITATIVE SCORING ENGINE
# =====================================================================
def analyze_asset(stock_df):
    """Processes pricing data to generate option strategies and volatility guards."""
    close_series = stock_df['CLOSE']
    current_price = float(close_series.iloc[-1])
    
    sma20 = float(close_series.rolling(min(20, len(close_series))).mean().iloc[-1])
    
    highs = stock_df['HIGH']
    lows = stock_df['LOW']
    atr = float((highs - lows).rolling(min(14, len(stock_df))).mean().iloc[-1])
    if atr <= 0: 
        atr = current_price * 0.01 
        
    if current_price > sma20:
        action = "CALL"
        stoploss = current_price - (1.5 * atr)
        target1 = current_price + (2.0 * atr)
        target2 = current_price + (4.0 * atr)
    else:
        action = "PUT"
        stoploss = current_price + (1.5 * atr)
        target1 = current_price - (2.0 * atr)
        target2 = current_price - (4.0 * atr)
        
    return {
        "Action": action,
        "Entry": round(current_price, 2),
        "Stoploss": round(stoploss, 2),
        "Target 1": round(target1, 2),
        "Target 2": round(target2, 2)
    }

# =====================================================================
# INTERFACE EXECUTION LAYER
# =====================================================================
st.title("🛡️ Institutional Multi-Layer Analytics Engine")

st.subheader("🌐 Core Channel Gateways STATUS")
col1, col2 = st.columns(2)

with col1:
    with st.spinner("Checking yfinance channel..."):
        yf_status = verify_yfinance_api()
    if yf_status == "YES":
        st.success("**FIRST ENTRY:** yfinance API Connection ➔ **YES**")
    else:
        st.error("**FIRST ENTRY:** yfinance API Connection ➔ **NO**")

with col2:
    with st.spinner("Checking Exchange data stream..."):
        nse_status = verify_nse_exchange_api()
    if nse_status == "YES":
        st.success("**SECOND ENTRY:** Direct Exchange Data Stream ➔ **YES**")
    else:
        st.error("**SECOND ENTRY:** Direct Exchange Data Stream ➔ **NO**")

st.markdown("---")

if yf_status == "YES" and nse_status == "YES":
    st.info("⚡ **System Status:** All production pipelines are linked. Quantitative Matrix Enabled.")
    
    if st.button("🚀 Run Institutional Matrix Scan"):
        watch_list = ["RELIANCE", "SBIN", "TCS", "INFY", "TATAMOTORS", "ITC"]
        compiled_matrix = []
        
        with st.spinner("Compiling asset vectors through structural data pool..."):
            for asset in watch_list:
                stock_data = get_equity_history(asset)
                if stock_data is not None and len(stock_data) > 0:
                    analysis = analyze_asset(stock_data)
                    analysis["Symbol"] = asset
                    compiled_matrix.append(analysis)
                    
            if compiled_matrix:
                df_display = pd.DataFrame(compiled_matrix)
                ordered_cols = ["Symbol", "Action", "Entry", "Stoploss", "Target 1", "Target 2"]
                st.dataframe(df_display[ordered_cols], use_container_width=True)
                st.success("Option Matrix calculated successfully from institutional feeds.")
            else:
                st.error("Matrix execution halted: Core data blocks missing variables.")
else:
    st.warning("🚨 **System Status:** Scanner disabled. One or more external data bridges are offline.")
